import { z } from "zod";
export const stages = ["IMPORTED", "SCHEDULED", "FIRST_CONTACT_SENT", "WAITING_CUSTOMER", "RESPONDED", "AI_CONVERSATION", "FOLLOW_UP", "QUALIFIED", "INTEREST_IDENTIFIED", "HUMAN_HANDOFF", "NEGOTIATION", "WON", "LOST", "NOT_INTERESTED", "DO_NOT_CONTACT"] as const;
export const stageLabels: Record<(typeof stages)[number], string> = { IMPORTED: "Importado", SCHEDULED: "Programado", FIRST_CONTACT_SENT: "Primeiro contato enviado", WAITING_CUSTOMER: "Aguardando resposta", RESPONDED: "Respondeu", AI_CONVERSATION: "Em conversa com IA", FOLLOW_UP: "Follow-up", QUALIFIED: "Qualificado", INTEREST_IDENTIFIED: "Interesse identificado", HUMAN_HANDOFF: "Transferido para humano", NEGOTIATION: "Em negociação", WON: "Fechado", LOST: "Perdido", NOT_INTERESTED: "Sem interesse", DO_NOT_CONTACT: "Não contatar" };
const text = (max: number) => z.string().trim().min(1).max(max);
export const playbookInterpretationSchema = z.strictObject({ understanding: text(1500), objective: text(1000), tone: text(300), allowedTopics: z.array(text(300)).max(15), avoidedTopics: z.array(text(300)).max(15), progressionRules: z.array(text(500)).min(1).max(15), followUpCriteria: z.array(text(500)).max(10), handoffCriteria: z.array(text(500)).min(1).max(15), firstMessages: z.array(text(800)).min(1).max(5), replyExamples: z.array(text(800)).max(5), forbiddenMessages: z.array(text(800)).max(5) });
export const playbookCreateSchema = z.strictObject({ name: text(160), instruction: text(6000) });
export const playbookActionSchema = z.discriminatedUnion("action", [z.strictObject({ action: z.literal("edit"), expectedVersion: z.number().int().min(0), instruction: text(6000), interpretation: playbookInterpretationSchema.nullable() }), z.strictObject({ action: z.literal("approve"), expectedVersion: z.number().int().min(0), confirmed: z.literal(true) })]);
export const sourceSchema = z.url().refine((url) => new URL(url).protocol === "https:", "Informe a fonte HTTPS.");
export const productKinds = ["NEW_LOAN", "REFINANCING", "PORTABILITY", "PAYROLL_CARD", "BENEFIT_CARD", "OTHER"] as const;
export const conditionTermsSchema = z.strictObject({ monthlyRatePercent: z.string().regex(/^\d{1,2}(\.\d{1,4})?$/).nullable(), annualCetPercent: z.string().regex(/^\d{1,3}(\.\d{1,4})?$/).nullable(), minMonths: z.number().int().min(1).max(600).nullable(), maxMonths: z.number().int().min(1).max(600).nullable(), requirements: z.array(text(500)).max(20), documents: z.array(text(300)).max(20), restrictions: z.array(text(500)).max(20) }).refine((v) => v.minMonths === null || v.maxMonths === null || v.minMonths <= v.maxMonths, "Prazo inválido.");
export const catalogCreateSchema = z.discriminatedUnion("kind", [z.strictObject({ kind: z.literal("institution"), name: text(160), source: sourceSchema }), z.strictObject({ kind: z.literal("product"), institutionId: text(100), name: text(160), productKind: z.enum(productKinds), description: text(1500) }), z.strictObject({ kind: z.literal("condition"), productId: text(100), agreement: text(300), terms: conditionTermsSchema, disclosure: text(1500), source: sourceSchema, validFrom: z.iso.datetime({ offset: true }), validUntil: z.iso.datetime({ offset: true }) }).refine((v) => new Date(v.validUntil) > new Date(v.validFrom), "Vigência inválida.")]);
export const decisionSchema = z.strictObject({ intent: z.enum(["GREETING", "QUESTION", "INTEREST", "QUALIFIED", "BUSY", "NOT_INTERESTED", "OPT_OUT", "WRONG_NUMBER", "HUMAN_REQUEST", "COMPLAINT", "OTHER"]), stage: z.enum(stages), response: z.string().max(1200), summary: text(2000), handoff: z.boolean(), handoffReason: z.string().max(500).nullable(), followUpAt: z.iso.datetime({ offset: true }).nullable(), followUpReason: z.string().max(500).nullable(), evidenceIds: z.array(text(100)).max(20), conditionId: z.string().max(100).nullable(), productId: z.string().max(100).nullable() });
export const cadenceSchema = z.strictObject({ dailyLimit: z.number().int().min(1).max(10000), hourlyLimit: z.number().int().min(1).max(1000), newContactsLimit: z.number().int().min(0).max(10000), followUpLimit: z.number().int().min(0).max(10000), minIntervalSeconds: z.number().int().min(10).max(86400), days: z.array(z.number().int().min(0).max(6)).min(1).max(7), startHour: z.number().int().min(0).max(23), endHour: z.number().int().min(1).max(24), timeZone: z.string().max(100).refine((v) => { try { new Intl.DateTimeFormat("en",{timeZone:v}); return true; } catch { return false; } }) }).refine((v) => v.endHour > v.startHour && new Set(v.days).size === v.days.length && v.hourlyLimit <= v.dailyLimit, "Cadência inválida.");
export function classifyExplicitContactRequest(value: string) {
  const text = value.normalize("NFD").replace(/\p{Diacritic}/gu, "").toLowerCase().trim();
  if (/\b(nao (me )?(mande|envie|chame|contate)|nao quero (mais )?(receber|contato|mensagens)|pare de (me )?(chamar|mandar|enviar)|remova (meu|o meu)|sair da lista|descadastrar)\b/.test(text) || /^(pare|parar|stop|sair|cancelar)[.!\s]*$/.test(text)) return "OPT_OUT" as const;
  if (/\b(numero errado|nao sou (essa|esta) pessoa|nao conheco)\b/.test(text)) return "WRONG_NUMBER" as const;
  if (/\b(nao (tenho )?interesse|nao quero|agora nao)\b/.test(text)) return "NOT_INTERESTED" as const;
  return null;
}
export function outreachScore(input: { validPhone: boolean; confirmedPhone: boolean; hasName: boolean; previousRelationship: boolean; responded: boolean; lastContactAt: Date | null }, now = new Date()) {
  const reasons: string[] = []; let score = 0;
  for (const [eligible, points, reason] of [[input.validPhone, 30, "Telefone válido"], [input.confirmedPhone, 15, "Telefone confirmado"], [input.hasName, 10, "Nome disponível"], [input.previousRelationship, 20, "Relacionamento anterior registrado"], [input.responded, 15, "Histórico de resposta"], [!!input.lastContactAt && now.valueOf() - input.lastContactAt!.valueOf() < 365 * 86400_000, 10, "Contato nos últimos 12 meses"]] as const) if (eligible) { score += points; reasons.push(reason); }
  return { score, priority: score >= 70 ? "HIGH" : score >= 40 ? "MEDIUM" : "LOW", reasons, purpose: "Prioridade operacional de contato; não avalia aprovação ou risco de crédito." };
}
