"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
type Campaign = { id: string; name: string; objective: string; status: string; version: number; startsAt: string; endsAt: string; maxContactsPerDay: number; maxTurns: number; followUpHours: number | null; list: { name: string }; connection: { instanceName: string }; _count: { sessions: number } };
type Session = { id: string; control: string; version: number; handoffReason: string | null; conversationId: string | null; campaign: { name: string }; customer: { fullName: string }; turns: { id: string; kind: string; status: string; message: string | null; errorCode: string | null; createdAt: string }[] };
type Data = { configuration: { configured: boolean; enabled: boolean; outboundEnabled: boolean }; campaigns: Campaign[]; sessions: Session[]; lists: { id: string; name: string; _count: { members: number } }[]; connections: { id: string; instanceName: string; isDefault: boolean; lastState: string }[] };
const labels: Record<string, string> = { DRAFT: "Rascunho", ACTIVE: "Autorizada", PAUSED: "Pausada", ENDED: "Encerrada", AI: "Assistente virtual", HUMAN: "Equipe humana", STOPPED: "Contato encerrado", QUEUED: "Aguardando processamento", RUNNING: "Gerando mensagem", READY: "Texto pronto", SENT: "Aceito pelo WhatsApp", FAILED: "Falha — conferir", HANDOFF: "Encaminhado à equipe", CANCELLED: "Cancelado", INITIAL: "Primeiro contato", REPLY: "Resposta", FOLLOWUP: "Retorno" };
const date = (value: string) => new Date(value).toLocaleString("pt-BR", { timeZone: "America/Sao_Paulo" });
export function OutreachBoard({ tenantId, platform = false }: { tenantId: string; platform?: boolean }) {
  const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [refresh, setRefresh] = useState(0); const [review, setReview] = useState<Campaign | null>(null); const [confirmed, setConfirmed] = useState(false);
  const base = platform ? "/api/platform/outreach" : "/api/outreach"; const query = `?tenantId=${encodeURIComponent(tenantId)}`;
  useEffect(() => { const controller = new AbortController(); const load = async () => { try { const response = await fetch(`${base}${query}`, { cache: "no-store", signal: controller.signal, headers: { "x-tenant-id": tenantId } }); const value = await response.json(); if (!response.ok) throw new Error(value.error); if (!controller.signal.aborted) setData(value); } catch (error) { if (!controller.signal.aborted) setError(error instanceof Error ? error.message : "Consulta indisponível."); } }; void load(); const timer = setInterval(() => { if (!document.hidden) void load(); }, 10_000); return () => { controller.abort(); clearInterval(timer); }; }, [base, query, tenantId, refresh]);
  async function action(path: string, method: string, body: unknown) { setBusy(true); setError(""); try { const response = await fetch(`${base}${path}${query}`, { method, headers: { "Content-Type": "application/json", "x-tenant-id": tenantId }, body: JSON.stringify(body) }); const value = await response.json(); if (!response.ok) throw new Error(value.error ?? "Ação indisponível."); setRefresh((value) => value + 1); setReview(null); setConfirmed(false); return true; } catch (error) { setError(error instanceof Error ? error.message : "Falha de conexão."); return false; } finally { setBusy(false); } }
  async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const success = await action("", "POST", { requestKey: crypto.randomUUID(), name: form.get("name"), objective: form.get("objective"), listId: form.get("listId"), connectionId: form.get("connectionId"), maxContactsPerDay: Number(form.get("maxContactsPerDay")), maxTurns: Number(form.get("maxTurns")), startsAt: new Date().toISOString(), endsAt: new Date(String(form.get("endsAt"))).toISOString(), followUpHours: form.get("followUpHours") ? Number(form.get("followUpHours")) : null }); if (success) formElement.reset(); }
  if (!data) return <section className="card"><p>{error || "Consultando relacionamento…"}</p></section>;
  const pending = [!data.configuration.configured && "chave da IA", !data.configuration.enabled && "ativação da IA proativa", !data.configuration.outboundEnabled && "ativação dos envios"].filter(Boolean);
  return <>
    {pending.length > 0 && <div className="notice" role="status"><strong>Preparação disponível · operação aguardando ativação</strong><p>Pendente: {pending.join(", ")}. As campanhas podem ser preparadas e autorizadas; as conversas só começarão depois da ativação.</p></div>}
    {error && <p className="error" role="alert">{error}</p>}
    <div className="metrics-grid"><section className="card metric"><h2>Campanhas autorizadas</h2><strong>{data.campaigns.filter((item) => item.status === "ACTIVE").length}</strong></section><section className="card metric"><h2>Com a assistente</h2><strong>{data.sessions.filter((item) => item.control === "AI").length}</strong></section><section className="card metric"><h2>Com a equipe</h2><strong>{data.sessions.filter((item) => item.control === "HUMAN").length}</strong></section><section className="card metric"><h2>Contatos encerrados</h2><strong>{data.sessions.filter((item) => item.control === "STOPPED").length}</strong></section></div><p className="muted">Visão das últimas 50 campanhas e dos últimos 50 relacionamentos.</p>
    <details className="card"><summary>Preparar nova campanha</summary><form className="form outreach-form" onSubmit={create}><label>Nome<input name="name" required minLength={3} maxLength={160} placeholder="Relacionamento com clientes" /></label><label>Público autorizado<select name="listId" required defaultValue=""><option value="">Selecione uma lista</option>{data.lists.map((item) => <option key={item.id} value={item.id}>{item.name} · {item._count.members} clientes</option>)}</select></label><label>Conexão WhatsApp<select name="connectionId" required defaultValue={data.connections.find((item) => item.isDefault)?.id ?? ""}><option value="">Selecione</option>{data.connections.map((item) => <option key={item.id} value={item.id}>{item.instanceName}{item.lastState === "OPEN" ? " · Conectada" : " · Aguardando conexão"}</option>)}</select></label><label>Objetivo da conversa<textarea name="objective" required minLength={10} maxLength={1200} placeholder="Entender o interesse dos clientes e encaminhar à equipe para atendimento." /></label><label>Novos contatos por dia<input name="maxContactsPerDay" type="number" min={1} max={20} defaultValue={10} required /></label><label>Máximo de mensagens por cliente<input name="maxTurns" type="number" min={1} max={12} defaultValue={6} required /></label><label>Validade (horário do dispositivo)<input name="endsAt" type="datetime-local" required /></label><label>Um retorno se não houver resposta<select name="followUpHours" defaultValue=""><option value="">Sem retorno automático</option><option value="24">Após 24 horas</option><option value="48">Após 48 horas</option><option value="72">Após 72 horas</option></select></label><p>Somente clientes com consentimento e um número válido entram no fluxo. A política da empresa define horários e intervalo entre contatos.</p><button disabled={busy || !data.lists.length || !data.connections.length}>Salvar rascunho</button></form></details>
    <section className="card"><h2>Campanhas</h2>{!data.campaigns.length && <p>Nenhuma campanha preparada.</p>}{data.campaigns.map((item) => <article className="crm-note" key={item.id}><div className="inbox-toolbar"><strong>{item.name}</strong><span className="status-badge">{labels[item.status]}</span></div><p>{item.list.name} · {item.connection.instanceName} · {item._count.sessions} relacionamentos</p><p>{item.objective}</p><p>{item.maxContactsPerDay} novos contatos/dia · Até {item.maxTurns} mensagens/cliente · Até {date(item.endsAt)}</p>{item.status !== "ENDED" && <div className="inbox-toolbar">{item.status !== "ACTIVE" && <button disabled={busy} onClick={() => { setReview(item); setConfirmed(false); }}>Revisar e autorizar</button>}{item.status === "ACTIVE" && <button className="secondary" disabled={busy} onClick={() => void action(`/${item.id}`, "PATCH", { action: "pause", expectedVersion: item.version })}>Pausar campanha</button>}<button className="secondary" disabled={busy} onClick={() => void action(`/${item.id}`, "PATCH", { action: "end", expectedVersion: item.version })}>Encerrar campanha</button></div>}</article>)}</section>
    {review && <section className="card" role="region" aria-label="Autorizar campanha"><h2>Autorizar {review.name}</h2><p><strong>{review.list.name}</strong> · {review.connection.instanceName}</p><p>{review.objective}</p><p>Até {review.maxContactsPerDay} novos clientes/dia e {review.maxTurns} mensagens por cliente, dentro da política da empresa. A validade termina em {date(review.endsAt)}. Clientes adicionados à lista depois desta autorização ficam fora desta rodada.</p><label><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} />Autorizo a assistente virtual a iniciar e continuar as conversas com este público, objetivo e limites.</label><div className="inbox-toolbar"><button disabled={busy || !confirmed} onClick={() => void action(`/${review.id}`, "PATCH", { action: "authorize", expectedVersion: review.version, confirmed: true })}>Confirmar autorização</button><button className="secondary" onClick={() => setReview(null)}>Voltar</button></div></section>}
    <section className="card"><h2>Relacionamentos e atendimento</h2>{!data.sessions.length && <p>As conversas aparecerão aqui quando a operação for ativada.</p>}{data.sessions.map((session) => <article className="crm-note" key={session.id}><strong>{session.customer.fullName} · {labels[session.control]}</strong><p>{session.campaign.name}{session.handoffReason && ` · ${session.handoffReason === "CUSTOMER_OPTED_OUT" ? "Cliente pediu para parar" : "Atendimento com a equipe"}`}</p>{session.control !== "STOPPED" && <button disabled={busy} onClick={() => void action(`/sessions/${session.id}`, "PATCH", { control: session.control === "AI" ? "HUMAN" : "AI", expectedVersion: session.version })}>{session.control === "AI" ? "Assumir atendimento" : "Devolver à assistente"}</button>}{session.conversationId && <Link href={`${platform ? "/platform" : "/app"}/conversations${query}`}> Abrir conversas →</Link>}<details><summary>Histórico das mensagens</summary>{session.turns.map((turn) => <div className="crm-note" key={turn.id}><small>{labels[turn.kind]} · {labels[turn.status]} · {date(turn.createdAt)}</small>{turn.message && <p>{turn.message}</p>}{turn.errorCode && <p>Este passo foi interrompido. Confira o contexto antes de retomar.</p>}</div>)}</details></article>)}</section>
  </>;
}
