"use client";
import { useState } from "react";
type User = { id: string; name: string; email: string; status: string; createdAt: string; memberships: { role: string; status: string }[]; teamMembers: { team: { name: string } }[] };
const roles: Record<string, string> = { TENANT_MASTER: "Administrador", TENANT_MANAGER: "Gestor", CONSULTANT: "Consultor", PLATFORM_ADMIN: "Plataforma" };
export function UserAdmin({ users, canManage = false }: { users: User[]; canManage?: boolean }) {
  const [error, setError] = useState(""); const [activation, setActivation] = useState(""); const [busy, setBusy] = useState(false);
  async function invite(formData: FormData) {
    setBusy(true); setError(""); setActivation("");
    try { const response = await fetch("/api/users", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(formData)) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setActivation(result.activationUrl); }
    catch (error) { setError(error instanceof Error ? error.message : "Falha ao convidar."); } finally { setBusy(false); }
  }
  async function update(id: string, input: { role?: string; status?: string }) {
    setBusy(true); setError("");
    try { const response = await fetch(`/api/users/${encodeURIComponent(id)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); location.reload(); }
    catch (error) { setError(error instanceof Error ? error.message : "Falha ao alterar acesso."); setBusy(false); }
  }
  return <>{canManage && <section className="card"><h2>Convidar usuário</h2><p>O titular define a própria senha. O convite vence em 48 horas.</p><form className="form" action={invite}><label>Nome<input name="name" minLength={2} maxLength={120} required /></label><label>E-mail<input name="email" type="email" required /></label><label>Perfil<select name="role"><option value="CONSULTANT">Consultor</option><option value="TENANT_MANAGER">Gestor</option><option value="TENANT_MASTER">Administrador</option></select></label><button disabled={busy}>Convidar</button></form>{activation && <div className="form"><label>Link de ativação<input value={activation} readOnly /></label><button type="button" onClick={() => void navigator.clipboard.writeText(activation).catch(() => setError("Copie o link manualmente."))}>Copiar link de ativação</button><button type="button" onClick={() => location.reload()}>Atualizar usuários</button></div>}</section>}{error && <p className="error" role="alert">{error}</p>}<section className="card"><div className="table-scroll"><table><thead><tr><th>Nome</th><th>E-mail</th><th>Perfil</th><th>Status do acesso</th><th>Equipes</th>{canManage && <th>Ações</th>}</tr></thead><tbody>{users.map((user) => { const member = user.memberships[0]; return <tr key={user.id}><td>{user.name}</td><td>{user.email}</td><td>{canManage && member?.role !== "PLATFORM_ADMIN" ? <select aria-label={`Perfil de ${user.name}`} disabled={busy} value={member?.role} onChange={(event) => void update(user.id, { role: event.target.value })}>{Object.entries(roles).filter(([role]) => role !== "PLATFORM_ADMIN").map(([role, label]) => <option key={role} value={role}>{label}</option>)}</select> : roles[member?.role] ?? "—"}</td><td>{member?.status === "ACTIVE" ? "Ativo" : member?.status === "INVITED" ? "Convite pendente" : "Suspenso"}</td><td>{user.teamMembers.map((item) => item.team.name).join(", ") || "—"}</td>{canManage && <td>{member?.role !== "PLATFORM_ADMIN" && <button disabled={busy || member?.status === "INVITED" || user.status !== "ACTIVE"} onClick={() => void update(user.id, { status: member?.status === "ACTIVE" ? "SUSPENDED" : "ACTIVE" })}>{member?.status === "ACTIVE" ? "Suspender acesso" : "Restaurar acesso"}</button>}</td>}</tr>; })}</tbody></table></div></section></>;
}
