import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { db } from "@/lib/db";
import { roleCapabilities, roleAccessScope, type AuthorizationContext } from "@/domain/access";
import { createPlaybook, changePlaybook, createCatalog, publishCondition, currentCreditKnowledge, listCommercial, enqueueCommercialJob, moveOpportunity, saveChannelCadence } from "@/services/commercial-service";
import { createOutreachCampaign, changeOutreachCampaign } from "@/services/outreach-service";
import { registerDoNotContact } from "@/services/commercial-events";
import { processCommercialAIBatch } from "@/services/commercial-ai-service";
import { enqueueEvolutionWebhook, processMessagingReceiptBatch } from "@/services/messaging-receipt-service";
import { connectionWebhookToken } from "@/integrations/evolution-webhook";
import { syntheticPlaybook } from "./fixtures/commercial";
import { assertTestHooksAllowed } from "@/services/test-hooks";
import { AuthorizationError } from "@/domain/errors";
async function main() {
  assertTestHooksAllowed(true);
  const schema = process.env.ACCEPTANCE_ISOLATED_SCHEMA;
  assert(schema && /^phase14_acceptance_[a-f0-9]{32}$/.test(schema)); assert.equal(new URL(process.env.DATABASE_URL!).searchParams.get("schema"), schema);
  process.env.OPENAI_API_KEY = ""; process.env.TYPESAFE_API_KEY = ""; process.env.JEV_ENABLED = "false";
  process.env.AI_OUTREACH_ENABLED = "false"; process.env.WHATSAPP_OUTBOUND_ENABLED = "false";
  process.env.EVOLUTION_WEBHOOK_SECRET = "synthetic-isolated-webhook-secret-32-characters";
  const started = Date.now(); const prefix = randomUUID().slice(0, 8);
  const tenant = await db.tenant.create({ data: { name: "Isolated commercial", slug: randomUUID() } });
  const foreign = await db.tenant.create({ data: { name: "Isolated foreign", slug: randomUUID() } });
  const user = await db.user.create({ data: { name: "Isolated administrator", email: randomUUID() + "@example.invalid", status: "ACTIVE" } });
  const master = await db.membership.create({ data: { tenantId: tenant.id, userId: user.id, role: "TENANT_MASTER", status: "ACTIVE" } });
  const context: AuthorizationContext = { tenantId: tenant.id, userId: user.id, membershipId: master.id, role: master.role, accessScope: roleAccessScope[master.role], capabilities: roleCapabilities[master.role] };
  const actor = { tenantId: tenant.id, context };
  const viewerUser = await db.user.create({ data: { name: "Isolated viewer", email: randomUUID() + "@example.invalid", status: "ACTIVE" } });
  const viewer = await db.membership.create({ data: { tenantId: tenant.id, userId: viewerUser.id, role: "VIEWER", status: "ACTIVE" } });
  const viewerActor = { tenantId: tenant.id, context: { ...context, userId: viewerUser.id, membershipId: viewer.id, role: viewer.role, capabilities: roleCapabilities[viewer.role] } };
  await assert.rejects(createPlaybook(viewerActor, { name: "Unauthorized", instruction: "Not allowed to write." }), AuthorizationError);
  await assert.rejects(listCommercial({ ...actor, tenantId: foreign.id }), AuthorizationError);
  let playbook = await createPlaybook(actor, { name: "Isolated strategy", instruction: "Inicie uma conversa leve e cordial. Verifique interesse sem prometer condições." });
  await assert.rejects(changePlaybook(actor, playbook.id, { action: "approve", expectedVersion: playbook.version, confirmed: true }));
  playbook = await changePlaybook(actor, playbook.id, { action: "edit", expectedVersion: playbook.version, instruction: playbook.instruction, interpretation: syntheticPlaybook });
  playbook = await changePlaybook(actor, playbook.id, { action: "approve", expectedVersion: playbook.version, confirmed: true });
  await assert.rejects(changePlaybook(actor, playbook.id, { action: "edit", expectedVersion: playbook.version, instruction: "Changed unauthorized strategy", interpretation: syntheticPlaybook }));
  const institution = await createCatalog(actor, { kind: "institution", name: "Institution fixture", source: "https://example.com/institution" });
  const product = await createCatalog(actor, { kind: "product", institutionId: institution.id, name: "Product fixture", productKind: "OTHER", description: "Fictitious product for SQL acceptance." });
  const terms = { monthlyRatePercent: null, annualCetPercent: null, minMonths: null, maxMonths: null, requirements: ["Synthetic requirement"], documents: [], restrictions: [] };
  const condition = await createCatalog(actor, { kind: "condition", productId: product.id, agreement: "Synthetic agreement", terms, disclosure: "Condição fictícia de aceitação; não é oferta comercial.", source: "https://example.com/condition", validFrom: new Date(Date.now() - 3600000).toISOString(), validUntil: new Date(Date.now() + 86400000).toISOString() });
  assert.equal((await db.$transaction((tx) => currentCreditKnowledge(tx, tenant.id))).length, 0);
  await publishCondition(actor, condition.id, 0, true);
  assert.equal((await db.$transaction((tx) => currentCreditKnowledge(tx, tenant.id))).length, 1);
  assert.equal((await db.$transaction((tx) => currentCreditKnowledge(tx, foreign.id))).length, 0);
  await assert.rejects(createCatalog(actor, { kind: "condition", productId: product.id, agreement: "Invalid", terms, disclosure: "Expired", source: "http://example.com", validFrom: new Date().toISOString(), validUntil: new Date(Date.now() - 1000).toISOString() }));
  const list = await db.customerList.create({ data: { tenantId: tenant.id, name: "10,000 synthetic contacts" } });
  const connections = Array.from({ length: 20 }, (_, i) => ({ id: "ch-" + prefix + "-" + i, tenantId: tenant.id, instanceName: "isolated_" + prefix + "_" + i }));
  await db.messagingConnection.createMany({ data: connections });
  for (let offset = 0; offset < 10000; offset += 1000) {
    const rows = Array.from({ length: 1000 }, (_, i) => ({ id: "contact-" + prefix + "-" + (offset + i), tenantId: tenant.id, fullName: "Synthetic contact " + (offset + i), displayName: "Synthetic contact " + (offset + i) }));
    await db.customer.createMany({ data: rows });
    await db.customerIdentifier.createMany({ data: rows.map((v, i) => ({ tenantId: tenant.id, customerId: v.id, type: "PHONE" as const, normalizedValue: "15555" + String(offset + i).padStart(6, "0"), verification: "CONFIRMED" as const })) });
    await db.customerListMember.createMany({ data: rows.map((v) => ({ tenantId: tenant.id, customerId: v.id, listId: list.id })) });
  }
  assert.equal(await db.customer.count({ where: { tenantId: tenant.id } }), 10000);
  assert.equal(await db.opportunity.count({ where: { tenantId: tenant.id } }), 0);
  const campaignInput = { requestKey: randomUUID(), name: "Synthetic campaign", objective: "Entender a necessidade sem oferecer condições inexistentes.", listId: list.id, connectionId: connections[0].id, playbookId: playbook.id, maxContactsPerDay: 1, maxTurns: 3, startsAt: new Date(Date.now() - 1000).toISOString(), endsAt: new Date(Date.now() + 86400000).toISOString(), followUpHours: null };
  const missingPlaybook = await createOutreachCampaign(actor, { ...campaignInput, requestKey: randomUUID(), playbookId: null });
  await assert.rejects(changeOutreachCampaign(actor, missingPlaybook.id, { action: "authorize", expectedVersion: 0, confirmed: true }));
  const campaign = await createOutreachCampaign(actor, campaignInput);
  await changeOutreachCampaign(actor, campaign.id, { action: "authorize", expectedVersion: 0, confirmed: true });
  const session = await db.outreachSession.create({ data: { tenantId: tenant.id, customerId: "contact-" + prefix + "-0", campaignId: campaign.id } });
  const sends = ["Não tenho interesse agora.", "Não quero mais receber mensagens.", "Pode me explicar melhor?", "Número errado."];
  for (let i = 0; i < 20; i++) {
    const conn = connections[i];
    const payload = { event: "messages.upsert", instance: conn.instanceName, data: { key: { id: "reply-" + i, remoteJid: "15555" + String(i).padStart(6, "0") + "@s.whatsapp.net", fromMe: false }, message: { conversation: sends[i % sends.length] }, messageTimestamp: Math.floor(Date.now() / 1000) } };
    await enqueueEvolutionWebhook(conn.id, connectionWebhookToken(conn.id), payload);
    await enqueueEvolutionWebhook(conn.id, connectionWebhookToken(conn.id), payload);
  }
  await Promise.all([processMessagingReceiptBatch(50), processMessagingReceiptBatch(50)]);
  assert.equal(await db.conversationMessage.count({ where: { tenantId: tenant.id } }), 20);
  assert.equal(await db.opportunity.count({ where: { tenantId: tenant.id } }), 20);
  assert.equal(await db.doNotContact.count({ where: { tenantId: tenant.id } }), 5);
  const notInterested = await db.opportunity.findUniqueOrThrow({ where: { sessionId: session.id } });
  assert.equal(notInterested.stage, "NOT_INTERESTED");
  assert.equal(await db.doNotContact.count({ where: { tenantId: tenant.id, phone: "15555000000" } }), 0);
  const disputed = await db.opportunity.findFirstOrThrow({ where: { customerId: "contact-" + prefix + "-2" } });
  await assert.rejects(moveOpportunity(viewerActor, disputed.id, { expectedVersion: disputed.version, stage: "NEGOTIATION", note: "Forbidden viewer write." }), AuthorizationError);
  const moved = await moveOpportunity(actor, disputed.id, { expectedVersion: disputed.version, stage: "NEGOTIATION", note: "Manual human review." }); assert.equal(moved.stage, "NEGOTIATION");
  await assert.rejects(moveOpportunity(actor, disputed.id, { expectedVersion: disputed.version, stage: "WON", note: "Stale version." }));
  await db.$transaction((tx) => registerDoNotContact(tx, tenant.id, "15555000000", "Isolated stop request", "TEST"));
  assert.equal((await db.outreachSession.findUniqueOrThrow({ where: { id: session.id } })).control, "STOPPED");
  const cadence = { dailyLimit: 20, hourlyLimit: 5, newContactsLimit: 10, followUpLimit: 5, minIntervalSeconds: 60, days: [1,2,3,4,5], startHour: 9, endHour: 18, timeZone: "America/Sao_Paulo" };
  await saveChannelCadence(actor, connections[0].id, cadence);
  await assert.rejects(saveChannelCadence(actor, connections[0].id, { ...cadence, hourlyLimit: 21 }));
  const waiting = await enqueueCommercialJob(actor, { kind: "TEST_AGENT", entityId: playbook.id, requestKey: randomUUID(), message: "Olá" });
  assert.equal(waiting.status, "WAITING_CONFIGURATION"); assert.equal(await processCommercialAIBatch(), 0);
  process.env.OPENAI_API_KEY = "synthetic-isolated";
  const jobInput = { kind: "TEST_AGENT", entityId: playbook.id, requestKey: randomUUID(), message: "Estou ocupado hoje." };
  const duplicateJobs = await Promise.all([enqueueCommercialJob(actor, jobInput), enqueueCommercialJob(actor, jobInput)]);
  assert.equal(duplicateJobs[0].id, duplicateJobs[1].id);
  const opening = await enqueueCommercialJob(actor, { kind: "TEST_AGENT", entityId: playbook.id, requestKey: randomUUID(), simulationStage: "INITIAL" });
  const openingPayload = (await db.commercialAIJob.findUniqueOrThrow({ where: { id: opening.id } })).payload as { simulationStage: string; message: string };
  assert.equal(openingPayload.simulationStage, "INITIAL"); assert.equal(openingPayload.message, "");
  await assert.rejects(enqueueCommercialJob(actor, { ...jobInput, simulationStage: "INITIAL", message: "" }), /outros dados/);
  const generator: Parameters<typeof processCommercialAIBatch>[0] = async (_kind, value) => {
    const input = value as { stage: string; objective: string; messages: { id: string }[] };
    if (input.stage === "INITIAL") { assert.equal(input.messages.length, 0); assert.equal(input.objective, syntheticPlaybook.objective); }
    return { result: { intent: input.stage === "INITIAL" ? "GREETING" : "BUSY", stage: input.stage === "INITIAL" ? "FIRST_CONTACT_SENT" : "FOLLOW_UP", response: input.stage === "INITIAL" ? "Oi, sou a Vanessa da BM Crédito. Podemos conversar?" : "Quando prefere conversar?", summary: "Simulação com cliente fictício.", handoff: false, handoffReason: null, followUpAt: null, followUpReason: null, evidenceIds: input.messages.map((item) => item.id), conditionId: null, productId: null }, trace: [], inputTokens: 50, outputTokens: 30, jev: null };
  };
  await Promise.all([processCommercialAIBatch(generator), processCommercialAIBatch(generator)]);
  assert.equal((await db.commercialAIJob.findUniqueOrThrow({ where: { id: duplicateJobs[0].id } })).status, "COMPLETED");
  const completedOpening = await db.commercialAIJob.findUniqueOrThrow({ where: { id: opening.id } });
  assert.equal(completedOpening.status, "COMPLETED");
  assert.equal((completedOpening.result as { messagesSent: number }).messagesSent, 0);
  assert.equal((completedOpening.result as { simulation: boolean }).simulation, true);
  assert.equal((await db.commercialAIJob.findUniqueOrThrow({ where: { id: waiting.id } })).status, "WAITING_CONFIGURATION");
  const dashboard = await listCommercial(actor); assert.equal(dashboard.counts.imported, 10000); assert.equal(dashboard.counts.opportunities, 20); assert.equal(dashboard.contacts.length, 100);
  assert.equal((await listCommercial(viewerActor)).canUpdate, false);
  await db.membership.update({ where: { id: viewer.id }, data: { status: "SUSPENDED" } }); await assert.rejects(listCommercial(viewerActor), AuthorizationError);
  assert.equal(await db.outboundDispatch.count(), 0);
  assert.equal(await db.messagingReceipt.count({ where: { status: "DEAD_LETTER" } }), 0);
  console.log("PHASE_14_ACCEPTANCE_JSON=" + JSON.stringify({ result: "PASS", connections: 20, contacts: 10000, observedReplies: 20, opportunities: 20, optOuts: 6, simulatedAIJobs: 2, initialSimulation: true, realOpenAICalls: 0, realJevCalls: 0, realOutboundCalls: 0, durationMs: Date.now() - started }));
}
void main().catch((error) => { console.error(error); process.exitCode = 1; }).finally(() => db.$disconnect());

