import { randomUUID } from "node:crypto";
import assert from "node:assert/strict";
import { db } from "@/lib/db";
import { roleCapabilities, type AuthorizationContext } from "@/domain/access";
import { AuthorizationError, ConflictError, NotFoundError } from "@/domain/errors";
import { createPlan, changePlan, listPlans } from "@/services/relationship-plan-service";
import { assertTestHooksAllowed } from "@/services/test-hooks";

async function main() {
  assertTestHooksAllowed(true);
  const schema = process.env.ACCEPTANCE_ISOLATED_SCHEMA;
  assert(schema && /^phase3_acceptance_[a-f0-9]{32}$/.test(schema));
  assert.equal(new URL(process.env.DATABASE_URL!).searchParams.get("schema"), schema);
  const suffix = randomUUID();
  const tenant = await db.tenant.create({ data: { name: "Synthetic Planner", slug: `planner-${suffix}` } });
  const foreign = await db.tenant.create({ data: { name: "Foreign Planner", slug: `foreign-${suffix}` } });
  const user = await db.user.create({ data: { name: "Synthetic Planner", email: `${suffix}@example.invalid`, status: "ACTIVE" } });
  const membership = await db.membership.create({ data: { tenantId: tenant.id, userId: user.id, role: "TENANT_MASTER", status: "ACTIVE" } });
  const context: AuthorizationContext = { tenantId: tenant.id, userId: user.id, membershipId: membership.id, role: "TENANT_MASTER", accessScope: "TENANT", capabilities: roleCapabilities.TENANT_MASTER };
  const foreignMembership = await db.membership.create({ data: { tenantId: foreign.id, userId: user.id, role: "TENANT_MASTER", status: "ACTIVE" } });
  const foreignContext = { ...context, tenantId: foreign.id, membershipId: foreignMembership.id };
  const customer = await db.customer.create({ data: { tenantId: tenant.id, displayName: "Synthetic Customer", fullName: "Synthetic Customer" } });
  const input = { customerId: customer.id, requestKey: randomUUID(), purpose: "Revisar necessidade", message: "Olá, gostaria de agendar uma conversa?", channel: "WHATSAPP" as const, scheduledAt: new Date(Date.now() + 3600_000).toISOString() };
  const [first, second] = await Promise.all([createPlan(context, input), createPlan(context, input)]);
  assert.equal(first.id, second.id);
  assert.equal(await db.relationshipPlan.count({ where: { tenantId: tenant.id } }), 1);
  assert.equal(await db.auditEvent.count({ where: { entityId: first.id, action: "RELATIONSHIP_PLAN_CREATED" } }), 1);
  await assert.rejects(createPlan(context, { ...input, purpose: "Changed" }), ConflictError);
  console.log(`PASS PLAN_IDEMPOTENCY ${JSON.stringify({ planId: first.id, count: 1, creationAudits: 1 })}`);
  await assert.rejects(createPlan({ ...context, tenantId: foreign.id }, { ...input, requestKey: randomUUID() }), AuthorizationError);
  await assert.rejects(createPlan(foreignContext, { ...input, requestKey: randomUUID() }), NotFoundError);
  assert.equal((await listPlans(foreignContext)).length, 0);
  await assert.rejects(changePlan(foreignContext, first.id, "approve"), NotFoundError);
  await assert.rejects(changePlan({ ...context, role: "CONSULTANT", capabilities: roleCapabilities.CONSULTANT }, first.id, "approve"), AuthorizationError);
  console.log("PASS PLAN_TENANT_ISOLATION_AND_RBAC");
  const approvals = await Promise.all([changePlan(context, first.id, "approve"), changePlan(context, first.id, "approve")]);
  assert(approvals.every((plan) => plan.status === "APPROVED" && plan.approvedById === user.id && plan.approvedAt));
  assert.equal(await db.auditEvent.count({ where: { entityId: first.id, action: "RELATIONSHIP_PLAN_APPROVED" } }), 1);
  assert.equal(await db.outboxEvent.count({ where: { aggregateId: first.id, eventType: "RELATIONSHIP_PLAN_APPROVED" } }), 1);
  console.log("PASS PLAN_APPROVAL_CONCURRENCY");
  await changePlan(context, first.id, "cancel");
  await changePlan(context, first.id, "cancel");
  await assert.rejects(changePlan(context, first.id, "approve"), ConflictError);
  assert.equal(await db.auditEvent.count({ where: { entityId: first.id, action: "RELATIONSHIP_PLAN_CANCELLED" } }), 1);
  const unchanged = await db.customer.findUniqueOrThrow({ where: { id: customer.id } });
  assert.equal(unchanged.relationshipState, "NEVER_CONTACTED");
  assert.equal(unchanged.lastContactAt, null);
  assert.equal(unchanged.lastOutboundAt, null);
  console.log("PASS PLAN_CANCELLATION_AND_CONTACT_SEMANTICS");
  await assert.rejects(createPlan(context, { ...input, requestKey: randomUUID(), scheduledAt: new Date(0).toISOString() }), ConflictError);
  const actions = await db.auditEvent.count({ where: { tenantId: tenant.id, entityId: first.id } });
  assert.equal(actions, 3);
  console.log(`PHASE_3_ACCEPTANCE_JSON=${JSON.stringify({ planId: first.id, concurrentRequests: 2, creationAudits: 1, approvalAudits: 1, cancellationAudits: 1, tenantIsolation: true, consultantDenied: true, unchangedContactState: true })}`);
  await db.$disconnect();
}
void main().catch(async (error: unknown) => { console.error(error); await db.$disconnect(); process.exitCode = 1; });
