import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import type { Role } from "@prisma/client";
import { db } from "@/lib/db";
import { roleCapabilities, roleAccessScope, type AuthorizationContext } from "@/domain/access";
import { createCRMCustomer, linkConversationCustomer, createCRMCase, changeCRMCase, listCRMCases, getCRMCase, distributionDirectory, assignCustomer, searchCRMCustomers, createCRMTeam, inviteCRMUser, addCRMTeamMember, crmSetupDirectory } from "@/services/crm-service";
import { CustomerService } from "@/services/customer-service";
import { TeamService } from "@/services/team-service";
import { recordObservedContact } from "@/services/observed-contact";

async function member(tenantId: string, role: Role) {
  const user = await db.user.create({ data: { name: `Synthetic ${role}`, email: `crm-${randomUUID()}@example.invalid`, status: "ACTIVE" } });
  const membership = await db.membership.create({ data: { tenantId, userId: user.id, role, status: "ACTIVE" } });
  const context: AuthorizationContext = { tenantId, userId: user.id, membershipId: membership.id, role, accessScope: roleAccessScope[role], capabilities: roleCapabilities[role] };
  return { tenantId, context };
}
async function main() {
  try {
    const schema = process.env.ACCEPTANCE_ISOLATED_SCHEMA;
    assert(schema && /^phase79_acceptance_[a-f0-9]{32}$/.test(schema)); assert.equal(new URL(process.env.DATABASE_URL!).searchParams.get("schema"), schema);
    const suffix = randomUUID();
    const tenant = await db.tenant.create({ data: { name: "Synthetic CRM", slug: `crm-${suffix}` } });
    const foreign = await db.tenant.create({ data: { name: "Foreign CRM", slug: `crm-foreign-${suffix}` } });
    const [master, managerA, managerB, consultantA, consultantB, consultantC, foreignMaster, admin] = await Promise.all([member(tenant.id, "TENANT_MASTER"), member(tenant.id, "TENANT_MANAGER"), member(tenant.id, "TENANT_MANAGER"), member(tenant.id, "CONSULTANT"), member(tenant.id, "CONSULTANT"), member(tenant.id, "CONSULTANT"), member(foreign.id, "TENANT_MASTER"), member(tenant.id, "PLATFORM_ADMIN")]);
    const platform = { tenantId: tenant.id, platformUserId: admin.context.userId };
    const preparedTeam = await createCRMTeam(platform, { name: "Prepared team" });
    const invite = await inviteCRMUser(platform, { email: `invite-${suffix}@example.invalid`, name: "Invited synthetic consultant", role: "CONSULTANT", teamId: preparedTeam.id });
    assert(invite.activationUrl.includes("/activate?token="));
    assert.equal((await db.membership.findUniqueOrThrow({ where: { id: invite.membershipId } })).status, "INVITED");
    await assert.rejects(inviteCRMUser(managerA, { email: `denied-${suffix}@example.invalid`, name: "Forbidden invitation", role: "CONSULTANT" }));
    await assert.rejects(crmSetupDirectory(consultantA));
    const added = await Promise.all([addCRMTeamMember(platform, { teamId: preparedTeam.id, membershipId: consultantC.context.membershipId }), addCRMTeamMember(platform, { teamId: preparedTeam.id, membershipId: consultantC.context.membershipId })]); assert.equal(added[0].id, added[1].id);
    const teamA = await db.team.create({ data: { tenantId: tenant.id, name: "Team A" } }); const teamB = await db.team.create({ data: { tenantId: tenant.id, name: "Team B" } });
    const foreignTeam = await db.team.create({ data: { tenantId: foreign.id, name: "Foreign team" } });
    for (const actor of [managerA, consultantA, consultantB]) await db.teamMember.create({ data: { tenantId: tenant.id, teamId: teamA.id, userId: actor.context.userId } });
    for (const actor of [managerB, consultantC]) await db.teamMember.create({ data: { tenantId: tenant.id, teamId: teamB.id, userId: actor.context.userId } });
    const customerInput = { requestKey: randomUUID(), fullName: "Synthetic customer private-name" };
    const customers = await Promise.all([createCRMCustomer(master, customerInput), createCRMCustomer(master, customerInput)]); assert.equal(customers[0].id, customers[1].id);
    const customer = customers[0];
    await assert.rejects(createCRMCustomer(master, { ...customerInput, fullName: "Changed name" }), /outros dados/);
    const second = await createCRMCustomer(platform, { requestKey: randomUUID(), fullName: "Unassigned synthetic customer" });
    assert.equal((await db.customer.findUniqueOrThrow({ where: { id: customer.id } })).relationshipState, "NEVER_CONTACTED");
    const connection = await db.messagingConnection.create({ data: { tenantId: tenant.id, instanceName: `crm_${suffix}` } });
    const conversation = await db.conversation.create({ data: { tenantId: tenant.id, connectionId: connection.id, remoteJid: "123456789@lid", lastMessageAt: new Date() } });
    const observedAt = new Date(Date.now() - 1000);
    await db.conversationMessage.create({ data: { tenantId: tenant.id, connectionId: connection.id, conversationId: conversation.id, providerMessageId: "crm-observed-1", direction: "INBOUND", kind: "TEXT", text: "synthetic-private-conversation", occurredAt: observedAt } });
    const createInput = { requestKey: randomUUID(), customerId: customer.id, conversationId: conversation.id, title: "Synthetic case" };
    await assert.rejects(createCRMCase(master, createInput));
    await Promise.all([linkConversationCustomer(master, conversation.id, customer.id), linkConversationCustomer(master, conversation.id, customer.id)]);
    await assert.rejects(linkConversationCustomer(master, conversation.id, second.id), /outro cliente/);
    const linked = await db.customer.findUniqueOrThrow({ where: { id: customer.id } }); assert.equal(linked.relationshipState, "CONTACTED"); assert.equal(linked.lastInboundAt?.valueOf(), observedAt.valueOf());
    await db.$transaction((transaction) => recordObservedContact(transaction, tenant.id, customer.id, "INBOUND", new Date(observedAt.valueOf() - 600_000)));
    assert.equal((await db.customer.findUniqueOrThrow({ where: { id: customer.id } })).lastContactAt?.valueOf(), observedAt.valueOf());
    const cases = await Promise.all([createCRMCase(master, createInput), createCRMCase(master, createInput)]); assert.equal(cases[0].id, cases[1].id); const caseId = cases[0].id;
    await assert.rejects(createCRMCase(master, { ...createInput, title: "Changed title" }), /outros dados/);
    await assert.rejects(createCRMCase(master, { ...createInput, requestKey: randomUUID() }), /atendimento aberto/);
    await createCRMCase(platform, { requestKey: randomUUID(), customerId: second.id, title: "Manual case without contact" });
    assert.equal((await db.customer.findUniqueOrThrow({ where: { id: second.id } })).relationshipState, "NEVER_CONTACTED");
    await assert.rejects(createCRMCase(consultantA, { requestKey: randomUUID(), customerId: second.id, title: "Forbidden case" }));
    assert.equal((await listCRMCases(consultantA)).total, 0);
    let assignment = await assignCustomer(master, customer.id, { teamId: teamA.id, assignedMembershipId: null, expectedVersion: null });
    await assert.rejects(assignCustomer(platform, customer.id, { teamId: preparedTeam.id, assignedMembershipId: invite.membershipId, expectedVersion: assignment.version }), /ativo/);
    assert.equal((await listCRMCases(managerA)).total, 1); assert.equal((await listCRMCases(managerB)).total, 0);
    await assert.rejects(assignCustomer(managerB, customer.id, { teamId: teamB.id, assignedMembershipId: consultantC.context.membershipId, expectedVersion: assignment.version }));
    await assert.rejects(assignCustomer(master, customer.id, { teamId: teamA.id, assignedMembershipId: consultantC.context.membershipId, expectedVersion: assignment.version }), /pertencer/);
    const assigned = await Promise.all([assignCustomer(managerA, customer.id, { teamId: teamA.id, assignedMembershipId: consultantA.context.membershipId, expectedVersion: assignment.version }), assignCustomer(managerA, customer.id, { teamId: teamA.id, assignedMembershipId: consultantA.context.membershipId, expectedVersion: assignment.version })]);
    assert.equal(assigned[0].version, 1); assert.equal(assigned[1].version, 1); assignment = assigned[0];
    assert.equal((await listCRMCases(consultantA)).total, 1); assert.equal((await listCRMCases(consultantB)).total, 0);
    assert.equal((await getCRMCase(consultantA, caseId)).conversation?.messages[0].text, "synthetic-private-conversation");
    assert.equal((await new CustomerService().list(consultantA.context)).total, 1);
    assert.equal(await new CustomerService().get(consultantA.context, second.id), null);
    assert.equal((await new CustomerService().list(managerB.context)).total, 0);
    assert.equal((await searchCRMCustomers(consultantA)).length, 1);
    await assert.rejects(getCRMCase(foreignMaster, caseId)); await assert.rejects(getCRMCase({ ...platform, tenantId: foreign.id }, caseId));
    await assert.rejects(distributionDirectory(consultantA)); assert.equal((await distributionDirectory(managerA))[0].id, teamA.id);
    await assert.rejects(new TeamService().addMember(managerB.context, teamA.id, consultantC.context.userId));
    await assert.rejects(db.customerAssignment.update({ where: { id: assignment.id }, data: { teamId: foreignTeam.id } }));
    await assert.rejects(db.customerAssignment.update({ where: { id: assignment.id }, data: { assignedMembershipId: foreignMaster.context.membershipId } }));
    const note = { action: "note" as const, requestKey: randomUUID(), expectedVersion: 0, note: "synthetic-private-note" };
    const notes = await Promise.all([changeCRMCase(consultantA, caseId, note), changeCRMCase(consultantA, caseId, note)]); assert.equal(notes[0].version, 1); assert.equal(notes[1].version, 1);
    assert.equal(await db.cRMNote.count({ where: { caseId } }), 1);
    await assert.rejects(changeCRMCase(consultantA, caseId, { ...note, note: "Changed note" }), /outros dados/);
    assignment = await assignCustomer(managerA, customer.id, { teamId: teamA.id, assignedMembershipId: consultantB.context.membershipId, expectedVersion: assignment.version });
    await assert.rejects(getCRMCase(consultantA, caseId)); await assert.rejects(changeCRMCase(consultantA, caseId, { ...note, requestKey: randomUUID(), expectedVersion: 1 }));
    assert.equal((await new CustomerService().list(consultantA.context)).total, 0);
    await assert.rejects(changeCRMCase(consultantB, caseId, { action: "transition", requestKey: randomUUID(), expectedVersion: 1, status: "COMPLETED", note: "Invalid direct closure" }), /não é permitida/);
    let item = await changeCRMCase(consultantB, caseId, { action: "transition", requestKey: randomUUID(), expectedVersion: 1, status: "IN_PROGRESS", note: "Atendimento iniciado." });
    await assert.rejects(changeCRMCase(consultantB, caseId, { ...note, requestKey: randomUUID(), expectedVersion: 1 }), /mudou/);
    item = await changeCRMCase(consultantB, caseId, { action: "schedule", requestKey: randomUUID(), expectedVersion: item.version, dueAt: new Date(Date.now() + 3600_000).toISOString() }); assert(item.dueAt);
    await assert.rejects(changeCRMCase(consultantB, caseId, { action: "schedule", requestKey: randomUUID(), expectedVersion: item.version, dueAt: new Date(0).toISOString() }), /futura/);
    await new TeamService().removeMember(master.context, teamA.id, consultantB.context.userId);
    await assert.rejects(getCRMCase(consultantB, caseId));
    await new TeamService().addMember(master.context, teamA.id, consultantB.context.userId);
    await db.membership.update({ where: { id: consultantB.context.membershipId }, data: { status: "SUSPENDED" } }); await assert.rejects(getCRMCase(consultantB, caseId));
    await db.membership.update({ where: { id: consultantB.context.membershipId }, data: { status: "ACTIVE" } });
    item = await changeCRMCase(consultantB, caseId, { action: "transition", requestKey: randomUUID(), expectedVersion: item.version, status: "WAITING_CUSTOMER", note: "Aguardando informação do cliente." });
    item = await changeCRMCase(consultantB, caseId, { action: "transition", requestKey: randomUUID(), expectedVersion: item.version, status: "COMPLETED", note: "Solicitação esclarecida pelo atendente." }); assert(item.completedAt);
    await assert.rejects(changeCRMCase(consultantB, caseId, { ...note, requestKey: randomUUID(), expectedVersion: item.version }), /encerrado/);
    await db.team.update({ where: { id: teamA.id }, data: { status: "ARCHIVED" } }); await assert.rejects(getCRMCase(consultantB, caseId)); assert.equal((await listCRMCases(managerA)).total, 0);
    for (const value of [JSON.stringify(await db.auditEvent.findMany()), JSON.stringify(await db.outboxEvent.findMany())]) for (const secret of ["synthetic-private-note", "synthetic-private-conversation", "private-name", "Solicitação esclarecida"]) assert(!value.includes(secret));
    console.log(JSON.stringify({ result: "PASS", phases: [7, 8, 9], concurrentCustomerCaseNoteAssignmentDedup: true, deterministicStagesAndReturns: true, observedContactOnly: true, tenantAndTeamForeignKeys: true, consultantAssignedOnly: true, reassignmentAndRevocationProtected: true, sourceConversationScoped: true, auditOutboxContentExcluded: true, messagesSent: 0, openAICalls: 0 }));
  } finally { await db.$disconnect(); }
}
void main().catch((error) => { console.error(JSON.stringify({ result: "FAIL", error: error instanceof assert.AssertionError ? error.message : error instanceof Error ? error.message : "CRM acceptance failed" })); process.exitCode = 1; });
